---
- name: Configuracion audit rotate
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: colocar rotate en auditd
      ansible.builtin.shell: |
        sed -i 's/^max_log_file_action = keep_logs/max_log_file_action = rotate/g' /etc/audit/auditd.conf


    - name: colocar rotate en auditd
      ansible.builtin.shell: |
        sed -i 's/^space_left_action = email/space_left_action = rotate/g' /etc/audit/auditd.conf

    - name: colocar rotate en auditd
      ansible.builtin.shell: |
        sed -i 's/^admin_space_left_action = halt/admin_space_left_action = SUSPEND/g' /etc/audit/auditd.conf

    - name: stop auditd services
      ansible.builtin.service:
         name: auditd
         state: stopped

    - name: stard auditd services
      ansible.builtin.service:
         name: auditd
         state: started
